-- MySQL Script generated by MySQL Workbench
-- Tue Jul 19 17:48:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `astree_db` DEFAULT CHARACTER SET utf8 ;
USE `astree_db` ;

-- -----------------------------------------------------
-- Table `astree_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`user` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `hashedpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `astree_db`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`profile` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`profile` (
  `profile_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `telescope` VARCHAR(45) NULL,
  `camera` VARCHAR(45) NULL,
  `biography` MEDIUMTEXT NULL,
  `image_url` VARCHAR(45) NULL,
  `image_alt` VARCHAR(45) NULL,
  PRIMARY KEY (`profile_id`),
  INDEX `fk_profile_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `astree_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`photo` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `dpt_location` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `profile_id` INT UNSIGNED NOT NULL,
  `photo_url` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`photo_id`, `profile_id`),
  UNIQUE INDEX `id_UNIQUE` (`photo_id` ASC) VISIBLE,
  INDEX `fk_post_profile1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `astree_db`.`profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`events` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`events` (
  `id_events` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `target` VARCHAR(80) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `profile_profile_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_events`, `profile_profile_id`),
  INDEX `fk_events_profile1_idx` (`profile_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_profile1`
    FOREIGN KEY (`profile_profile_id`)
    REFERENCES `astree_db`.`profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`events_has_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`events_has_profile` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`events_has_profile` (
  `events_id_events` INT UNSIGNED NOT NULL,
  `profile_profile_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`events_id_events`, `profile_profile_id`),
  INDEX `fk_events_has_profile_profile1_idx` (`profile_profile_id` ASC) VISIBLE,
  INDEX `fk_events_has_profile_events1_idx` (`events_id_events` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_profile_events1`
    FOREIGN KEY (`events_id_events`)
    REFERENCES `astree_db`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_profile_profile1`
    FOREIGN KEY (`profile_profile_id`)
    REFERENCES `astree_db`.`profile` (`profile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
