-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 21:59:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `astree_db` DEFAULT CHARACTER SET utf8 ;
USE `astree_db` ;

-- -----------------------------------------------------
-- Table `astree_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`user` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `hashedpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

INSERT INTO `user`(`user_id`, `email`, `hashedpassword`) VALUES
(1,"genin.alexandre@live.fr", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ');
(2,"kevin.lavigne@gmail.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ');



-- -----------------------------------------------------
-- Table `astree_db`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`profile` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  `telescope` VARCHAR(45) NULL,
  `camera` VARCHAR(45) NULL,
  `biography` MEDIUMTEXT NULL,
  `image_url` VARCHAR(45) NULL,
  `image_alt` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `profile_id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `astree_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`photo` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` DATE NOT NULL,
  `dpt_location` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `photo_url` VARCHAR(200) NOT NULL,
  `city_location` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `profile_id`),
  UNIQUE INDEX `id_UNIQUE` (`photo_id` ASC) VISIBLE,
  INDEX `fk_photo_profile1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `astree_db`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`events` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`events` (
  `id_events` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `dpt_location` VARCHAR(45) NOT NULL,
  `target` VARCHAR(80) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_events`),
  UNIQUE INDEX `id_events_UNIQUE` (`id_events` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`profile_has_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`profile_has_events` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`profile_has_events` (
  `profile_profile_id` INT NOT NULL,
  `events_id_events` INT NOT NULL,
  PRIMARY KEY (`profile_profile_id`, `events_id_events`),
  INDEX `fk_profile_has_events_events1_idx` (`events_id_events` ASC) VISIBLE,
  INDEX `fk_profile_has_events_profile1_idx` (`profile_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_events_profile1`
    FOREIGN KEY (`profile_profile_id`)
    REFERENCES `astree_db`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_events_events1`
    FOREIGN KEY (`events_id_events`)
    REFERENCES `astree_db`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
