-- MySQL Script generated by MySQL Workbench
-- Wed Jul 20 21:59:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema astree_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `astree_db` DEFAULT CHARACTER SET utf8 ;
USE `astree_db` ;

-- -----------------------------------------------------
-- Table `astree_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`user` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `hashedpassword` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);

INSERT INTO `user`(`user_id`, `email`, `hashedpassword`) VALUES
(1,"genin.alexandre@live.fr", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ'),
(2,"kevin.lavigne@gmail.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ'),
(3,"scarlettjohannson@wonder.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ'),
(4,"randomuser@random.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ'),
(5,"erwan.mcgreggor@gmail.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ'),
(6,"steven.gerrard@gmail.com", '$argon2id$v=19$m=65536,t=5,p=1$RghFSPxGNFoW2FyGliiPQw$a490HeN/yGiJDl1tWpJnaqZehOBXbyOzf43LB+lkzJQ');



-- -----------------------------------------------------
-- Table `astree_db`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`profile` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `pseudo` VARCHAR(45) NULL,
  `sexe` VARCHAR(45) NULL,
  `age` INT NULL,
  `city` VARCHAR(45) NULL,
  `telescope` VARCHAR(45) NULL,
  `camera` VARCHAR(45) NULL,
  `monture` VARCHAR(100) NULL,
  `biography` MEDIUMTEXT NULL,
  `image_url` VARCHAR(200) NULL,
  `image_alt` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `profile_id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `astree_db`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `profile` (`id`, `user_id`, `pseudo`, `sexe`, `age`, `city`, `telescope`, `camera`,`monture`, `biography`, `image_url`, `image_alt` ) VALUES
(1, 1, 'Disrupt3d','Homme', 32,'Avignon', 'skywatcher 150/750','canon D720', NULL, "Amateur de astrophotographie et des étoiles, j'ai acquis mon premier télescope il y a 8 mois.", 'https://i.ibb.co/BcLNh2Q/AG-PROFIL-2.jpg', 'photo de profil'),
(2, 2, '3vilAngel','Homme', 24,'Hautevesnes', 'Omegon N 150/750 EQ-3','CANON EOS 6D MARK II', NULL, "je m'apelle Kévin, je suis un otp BRAND qui int sans vergogne mon ADC", 'https://i.ibb.co/H2vkkqc/brandloadscreen-7-skins-brand-skin07.jpg', 'photo de profil'),
(3, 3, 'Beautiful_Scarlet','Femme',41,'Saint-Tropez', 'Dobson Orion N 356/1650','SONY Alpha a6000', NULL, "Hi there, i'am a begeener in astropics,and i just wanna  find some new content for my instagram account.Would love to  participe events and watch the sky with you guys!", 'https://i.ibb.co/z20mXPg/scarlett-johannson.jpg', 'photo de profil'),
(4, 4, null,'Homme', NULL, 'Paris', 'Celestron PowerSeeker 127 EQ','Panasonic LUMIX G7', NULL, "j'ai attéri là un peu par hasard", null, null),
(5, 5, 'Ewan_MC','Homme',52,'Tatoine', 'SEBEN 14/1000 EQ3','Nikon D3500', NULL, "Hi there", 'https://i.ibb.co/W5Q2pKd/ewan-mc.jpg', 'photo de profil'),
(6, 6, 'SG8_YNWA','Homme',37,'Liverpool', 'Omegon Dobson N 203/1200 DOB','Pentax K-70', 'Skywatcher EQ3-2', "Hi there, i ma stevie from Liverpool.i used to be a legend at Liverpool FC , where i played for almost 20 years and made history. i retired at  34 and begun a new career as a football coach . i had succes taking charge of Glasgow Rangers, then  i  accepted a move to Aston villa which signed my return in premier league . I am currently waiting my turn to coach liverpool , but  Klopp seems to be not decided yet . its a bit long and boring , so  i started to watch the sky and  looking for  amazing scenes .", 'https://i.ibb.co/zxNvCsr/steven-gerrard.jpg', 'photo de profil');






-- -----------------------------------------------------
-- Table `astree_db`.`photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`photo` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`photo` (
  `photo_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `date` VARCHAR(10) NOT NULL,
  `dpt_location` VARCHAR(2) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `photo_url` VARCHAR(200) NOT NULL,
  `photo_alt` VARCHAR(100) NOT NULL,
  `city_location` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `profile_id`),
  UNIQUE INDEX `id_UNIQUE` (`photo_id` ASC) VISIBLE,
  INDEX `fk_photo_profile1_idx` (`profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_photo_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `astree_db`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `photo` (`photo_id`, `title`, `date`, `dpt_location`, `description`, `photo_url`, `photo_alt`,`city_location`, `profile_id`) VALUES
(1, "Galaxie d'andromède",'12/07/22', '73',"La météo annonçait une nuit clémente hier soir, j'ai donc sorti mon perl 150/750. Je fais de l'astrophotograhie depuis environ 1mois, et je voulais donc tenter pour la première fois de faire l'iconique galaxie d'andromede.Finalement le ciel était un peu voilé, et une bonne moitié de lune était présente à partir de 00h30. J'ai quand même pu réaliser environ 4h de temps de pose.Iso 800 30 darks, flats, offsets Pretraitement & traitement siril Post traitement gimp Perl 150/750 Eq 3-2 motorisée en ad Canon eos 550d", 'https://i.ibb.co/dMKpsBf/galaxy-andromede.jpg', "la galaxie d'andromede", 'Annecy', 1),
(2, "Nébuleuse L16",'17/07/22', '84',"Photo prise avec un SW150/750 sur montuire EQ3.2 motorisée RA et canon 1300d non défiltré. 110 poses de 30s ISO800 entre 0h30 et 2h environ.20 DARKS/ FLAT /OFFSET.traitement sur SIRIL et GIMP.Je suis assez satisfait du résultat vu sa position très basse sur l'horizon et du seeing pas fou fou  ", 'https://i.ibb.co/ZgT5WwV/nebuleuse-m16.jpg', "la nebuleuse M16", 'Avignon', 3),
(3, "Nébuleuse M45",'07/06/22', '13',"Le set-up:lunette skywatcher 80ed/correcteur-réducteur 0.85/ asi 2600 mm/ RAF/DO avec asi 290 mini/AZEQ6/ pilotage via Asiair pro.Acquisitions: Luminance: 80*3min à gain 0. RVB: 1h par filtre avec sub de 3 min à gain 0 DOF Traitement Pixinsight", 'https://i.ibb.co/nBXNpxW/M45.jpg', "la nebuleuse M45", 'Noves', 2),
(4, "Nébuleuse du Sorcier NGC7380",'19/07/22', '60'," le sorcier en 6 heures sur deux soirs.eq5 eqstar SW130PDS ASI533MC + altair tri-bande, autoguidage PHD2 sur lunette guidée. poses unitaire de 180 secondes, sur 6 heures au total.traitement Siril, starnet, PS, LR", 'https://i.ibb.co/phh3Sk5/NGC7380-sorcier.jpg', "la nebuleuse du sorcier", 'Lille', 2),
(5, "Lune",'20/07/22', '30'," Photo prise avec Celestron C8, réducteur f6.3, asi294mc pro. 197 images stackées. ", 'https://i.ibb.co/Tqbs3Nx/lune.jpg',"la lune", 'Noves', 1),
(6, "M3 et comète Léonard",'03/04/22', '34',"Lunette Evostar 100 ED, Monture NEQ5 goto,réducteur 0,85,Canon 550 D non défilltré.8 poses de 40 secondes chacune,iso 800 traitement SIRIL ,GIMP.", 'https://i.ibb.co/JygJZTj/M3-leonard.jpg', "la M3 rencontre une comète", 'Lattes', 3),
(7, "supernova W63",'17/05/22',"77","Il s'agit donc du rémanent de Supernova SNR G82-2+5.3 (W63), en 47h20 de poses du 9 juin au 8 juillet 2022 à Amiens (France, Bortle 7).
L'objet étant une coquille d'oxygène ionisé sur fond d'une nébuleuse à émission composé majoritairement d'hydrogène ionisé, j'ai opté pour une composition HOO plutôt que SHO sur ce rémanent très faible et relativement peu imagé.", 'https://i.ibb.co/kM7vHPS/supernova.jpg',' rémanent de Supernova','Liverpool',6 ),
(8, "M106",'12/02/22',"34","ça faisait longtemps que je n'avais pas posté, suite à une période plus active en nightscape. Mais finalement ça fait du bien de revenir aux fondamentaux ! Voici une autre image qui date du mois de février peu après que nous aillons upgradé le setup avec Killian.
Dans cette image il resté du Bf à régler donc les étoiles tire un peu.Par contre on est vraiment dans l'exemple parfait d'un échantillonnage sympa avec du champ et de la résolution, c'est à dire que M106 est petite dans le champ mais la full permet de zoomer dessus en aillant des détails intéressants pour une lulu de 100mm.
Nous avion fait 5h de Ha mais je ne les ai pas intégrées, je trouvais que ça manquait encore de jus du coup on reposera surement plus tard dessus pour ajouter du HA.Place à l'image et à vos critiques et maintenant place aux Nuits du Causse Noir ! ;) 
420x120s en L, 96x120s en R, 101x120s en V, 96x120s en B.La full à 100% (26Millions de pixels )", 'https://i.ibb.co/YRG9xF7/Crop-thumb-jpg-257d56dc5b8127a655fab6cbc5a71c0d.jpg',' crop de M106','Argelliers',5 );


-- -----------------------------------------------------
-- Table `astree_db`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`events` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`events` (
  `id_events` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `date` DATE NOT NULL,
  `dpt_location` VARCHAR(45) NOT NULL,
  `target` VARCHAR(80) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_events`),
  UNIQUE INDEX `id_events_UNIQUE` (`id_events` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `astree_db`.`profile_has_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `astree_db`.`profile_has_events` ;

CREATE TABLE IF NOT EXISTS `astree_db`.`profile_has_events` (
  `profile_profile_id` INT NOT NULL,
  `events_id_events` INT NOT NULL,
  PRIMARY KEY (`profile_profile_id`, `events_id_events`),
  INDEX `fk_profile_has_events_events1_idx` (`events_id_events` ASC) VISIBLE,
  INDEX `fk_profile_has_events_profile1_idx` (`profile_profile_id` ASC) VISIBLE,
  CONSTRAINT `fk_profile_has_events_profile1`
    FOREIGN KEY (`profile_profile_id`)
    REFERENCES `astree_db`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_has_events_events1`
    FOREIGN KEY (`events_id_events`)
    REFERENCES `astree_db`.`events` (`id_events`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
